she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('edit-story/<int:pk>', views.UpdateStoryView.as_view(), name='updateStory'),
    path('delete-story/<int:pk>', views.DeleteStoryView.as_view(), name='deleteStory'),
    path('author-search/', views.searchAuthor.as_view(), name='authorSearch'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('', include('news.urls')),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, ViewAccount, UpdateAccount

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('<int:pk>', ViewAccount.as_view(), name='viewAccount'),
    path('create-account/edit', UpdateAccount.as_view(), name='updateAccount'),
    path('profile/<int:pk>/', ViewAccount.as_view(), name='profile'),
    # path('fav/<int:pk>/', views.favourite_add, name='favourite-add'),
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE, 
        related_name='posts',
    )
    pub_date = models.DateTimeField(default=timezone.now)
    content = models.TextField()
    image_url = models.URLField(blank=True)
    # favourites = models.ManyToManyField(get_user_model(), related_name='favourite', default=None, blank=True)

    class Meta:
        ordering = ('pub_date',)

    def __str__(self):
        return self.title

    

she_codes_news/users/models.py
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass
    def __str__(self):
        return self.username

# Create your models here.

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content', 'image_url']
        widgets = {
            'pub_date': forms.DateInput(format=('%m/%d/%Y'), 
            attrs={
                'class':'form-control', 
                'plageholder':'Select a date', 
                'type':'date'
                }),
        }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']


class CustomUserChangeForm(UserChangeForm):
    first_name = forms.CharField(max_length=50, required=False, help_text='Optional')
    last_name = forms.CharField(max_length=50, required=False, help_text='Optional')
    email = forms.EmailField(max_length=50, required=True, help_text='Required')

    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from django.views import generic
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import NewsStory
from users.models import CustomUser
from .forms import StoryForm

class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.all().order_by('-pub_date')
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

# Add view for editing/updating a news story
class UpdateStoryView(UpdateView):
    form_class = StoryForm
    model = NewsStory
    template_name = 'news/updateStory.html'
    success_url = reverse_lazy('news:index')

# Add view for deleting a news story
class DeleteStoryView(DeleteView):
    model = NewsStory
    template_name = 'news/deleteStory.html'
    success_url = reverse_lazy('news:index')

class searchAuthor(generic.ListView):
    template_name = 'news/authorSearch.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return CustomUser.objects.all()

    def get_context_data(self, **kwargs):
        query = self.request.GET.get("author")
        context = super().get_context_data(**kwargs)
        context['author_list'] = CustomUser.objects.all().order_by('username')
        context['all_stories'] = NewsStory.objects.all().order_by('-pub_date')
        context['author_stories'] = NewsStory.objects.filter(author__username=query).order_by('-pub_date')
        return context

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm, CustomUserChangeForm
# from news.models import NewsStory

# @ login_required
# def favourite_add(request, id):
#     NewsStory = get_object_or_404(NewsStory, id=id)
#     if NewsStory.favourites.filter(id=request.user.id).exists():
#         NewsStory.favourites.remove(request.user)
#     else:
#         NewsStory.favourites.add(request.user)
#     return HttpResponseRedirect(request.META['HTTP_REFERER'])


class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

    def form_valid(self,form):
        f=super().form_valid(form)
        user = self.get_object
        login(self.request, user)
        return f

class ViewAccount(generic.DetailView):
    model = CustomUser
    success_url = reverse_lazy('login')
    template_name = 'users/viewAccount.html'
    context_object_name = 'profile'

class UpdateAccount(UpdateView):
    form_class = CustomUserChangeForm
    model = CustomUser
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'
    context_object_name = 'update-account'

she_codes_news/news/templates/news/authorSearch.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    <h2>
        Filter Stories by Author
    </h2>
    <form action="" method="GET">
        <p>Select Author:
            <input name="author" type="text" list="author_list" placeholder="Select Author" autocomplete="off">
            <datalist id="author_list">
                <select name="Author">
                    {% for author in author_list %}
                        <option value="{{ author.username }}"></option>
                    {% endfor %}
                </select>
            </datalist>
            <input type="submit" value="Search">
        </p>
    </form>

    <ul>
    {% if request.GET.author %}
        <h2><a href="{% url 'users:profile' request.GET.author %}">{{ request.GET.author|capfirst }}'s Stories</a></h2> 
        {% if author_stories %}
            {% for story in author_stories %}
            <li><a href="{% url 'news:story' story.id %}">{{ story.title }}</a><em>{{ story.pub_date| date:"M d Y" }}</em></li>
            {% endfor %}
        {% else %}
            <p>There are no stories by this author</p>           
        {% endif %}
    {% else %}
        <h2>All Stories</h2>
        <em>Select an author to filter stories</em>
        {% for story in all_stories %}
            <li><a href="{% url 'news:story' story.id %}">{{ story.title }}</a><em>by {{ story.author.username|capfirst }}, {{ story.pub_date| date:"M d Y" }}</em></li>
        {% endfor %}        
    {% endif %}        
    </ul>

{% endblock %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>
{% else %}
<p class="authentication_error">You are not logged in!</p>
{% endif %}
{% endblock %}

she_codes_news/news/templates/news/deleteStory.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
{% if request.user.is_authenticated %}
    <h2>Are you sure you wish to delete your story?</h2>
    <p>"{{ newsstory.title }}" will be permanently deleted.</p>
    <p>This action cannot be undone!</p>
    <div>
        <form method="POST">
            {% csrf_token %}
            <button>
                Delete Story
            </button>
        </form>
    </div>
    {% else %}
    <h2>Only the author of this story can delete this story.</h2> 
    <a href="{% url 'login' %}">Log in here!</a>
{% endif %}
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" type="text/css" href="{% static 'news/styles.css' %}">


{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <a href="{% url 'news:newStory' %}">Write New Story</a>
{% endif %}
<a href="{% url 'news:authorSearch' %}">Filter Stories by Author</a>
<h2>Latest News</h2>

<div id="latest-stories">
    {% if latest_stories %}
        {% for story in latest_stories %}
            {% include "./storyCard.html" with story=story position=forloop.counter %}
        {% endfor %}
    {% else %}
        <p>No stories are available.</p>
    {% endif %}
</div> 

<div id="all-stories">
    {% if latest_stories %}
        {% for story in all_stories %}
            {% include "./storyCard.html" with story=story %}
            <p>{{ story.title }}</p>
        {% endfor %}
    {% else %}
        <p>No stories are available.</p>
    {% endif %}
</div>

{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
<script src="https://kit.fontawesome.com/1fb5edeab6.js" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>Written by: {{ story.author|capfirst }}</h4>
    {% if request.user.is_authenticated %}
        {% if request.user == story.author %}
            <a href="{% url 'news:updateStory' story.id %}" class="edit-story">Edit story</a>
        {% endif %}
    {% endif %}
    <a href="#"><svg id="outline-heart" class="heart-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" style="width:15px;"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M244 84L255.1 96L267.1 84.02C300.6 51.37 347 36.51 392.6 44.1C461.5 55.58 512 115.2 512 185.1V190.9C512 232.4 494.8 272.1 464.4 300.4L283.7 469.1C276.2 476.1 266.3 480 256 480C245.7 480 235.8 476.1 228.3 469.1L47.59 300.4C17.23 272.1 0 232.4 0 190.9V185.1C0 115.2 50.52 55.58 119.4 44.1C164.1 36.51 211.4 51.37 244 84C243.1 84 244 84.01 244 84L244 84zM255.1 163.9L210.1 117.1C188.4 96.28 157.6 86.4 127.3 91.44C81.55 99.07 48 138.7 48 185.1V190.9C48 219.1 59.71 246.1 80.34 265.3L256 429.3L431.7 265.3C452.3 246.1 464 219.1 464 190.9V185.1C464 138.7 430.4 99.07 384.7 91.44C354.4 86.4 323.6 96.28 301.9 117.1L255.1 163.9z"/></svg><svg id="solid-heart" class="heart-icon" xmlns="http://www.w3.org/2000/svg" style="width:15px;" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M47.6 300.4L228.3 469.1c7.5 7 17.4 10.9 27.7 10.9s20.2-3.9 27.7-10.9L464.4 300.4c30.4-28.3 47.6-68 47.6-109.5v-5.8c0-69.9-50.5-129.5-119.4-141C347 36.5 300.6 51.4 268 84L256 96 244 84c-32.6-32.6-79-47.5-124.6-39.9C50.5 55.6 0 115.2 0 185.1v5.8c0 41.5 17.2 81.2 47.6 109.5z"/></svg> Add to Favourites</a>
    <div id="story-content">
        <img src="{% static '/news/images/placeholder-5.jpg' %}" class="small_img">
        {{ story.content|linebreaks }}
    </div>
    {% if request.user.is_authenticated %}
        {% if request.user == story.author %}
            <button>
                <a href="{% url 'news:deleteStory' story.id %}" class="delete-story">Delete story</a>
            </button>
        {% endif %}
    {% endif %}
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id%}">
        {% if story.image_url %}
            <img src="{{ story.image_url }}.jpg">
        {% else %}
            <img src="https://picsum.photos/300?random={{ story.id }}">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author|capfirst }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/news/templates/news/updateStory.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<h2>Edit Your Story</h2>
{% if request.user.is_authenticated %}
    <div class="form">
        <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>
            Update Story
        </button>
        </form>
    </div>
{% else %}
<h2>Only the author of this story can make changes.</h2> 
<a href="{% url 'login' %}">Log in here!</a>
{% endif %}
{% endblock %}

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="author" content="Mandy Cook">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Noto+Sans:ital,wght@0,100;0,400;0,900;1,100&family=Raleway:ital@0;1&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}
        {% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        {% block content %}{% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'users:viewAccount' request.user.id %}">{{ user.username|capfirst }}</a>
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %} 

{% block content %}
<h2>Create Account</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Account</button>
</form>
<p>Already have an account?<span><a href="../login/">Return to login</a></span></p> 
{% endblock %}

she_codes_news/users/templates/users/viewAccount.html
{% extends 'base.html' %} 

{% block content %}

{% if request.user.is_authenticated %}
<h2>Welcome, {{ user.username|capfirst }}</h2>
<p>Name: {{ user.name|capfirst }}</p>
<p>Username: {{ user.username|capfirst }}</p>
<p>Email: {{ user.email }}</p>
<button>Edit Account</button><button>Delete Account</button>
{% endblock %}